# Imagen oficial de Ruby 2.7
FROM ruby:2.7

# Creamos el directorio de trabajo
WORKDIR /app

# Copiamos el contenido de la carpeta actual al directorio de trabajo
ADD . /app

# Instalamos las dependencias
RUN bundle install